BASE_ITEM_ID = 9901000


ITEM_MAPPING = {
	-- Weapons
	[BASE_ITEM_ID + 31] = { "sword", "toggle" },
	[BASE_ITEM_ID + 32] = { "broadsword", "toggle" },
	[BASE_ITEM_ID + 33] = { "magicsword", "toggle" },
	[BASE_ITEM_ID + 34] = { "club", "toggle" },
	[BASE_ITEM_ID + 35] = { "hammer", "toggle" },
	[BASE_ITEM_ID + 36] = { "throwingdaggers", "toggle" },
	[BASE_ITEM_ID + 37] = { "axe", "toggle" },
	[BASE_ITEM_ID + 38] = { "chickendrumstick", "toggle" },
	[BASE_ITEM_ID + 39] = { "crossbow", "toggle" },
	[BASE_ITEM_ID + 40] = { "longbow", "toggle" },
	[BASE_ITEM_ID + 41] = { "flaminglongbow", "toggle" },
	[BASE_ITEM_ID + 42] = { "magiclongbow", "toggle" },
	[BASE_ITEM_ID + 43] = { "spear", "toggle" },
	[BASE_ITEM_ID + 44] = { "lightning", "toggle" },
	[BASE_ITEM_ID + 45] = { "goodlightning", "toggle" },
	[BASE_ITEM_ID + 49] = { "dragonarmour", "toggle" },
	[BASE_ITEM_ID + 46] = { "shieldcopper", "toggle" },
	[BASE_ITEM_ID + 47] = { "shieldsilver", "toggle" },
	[BASE_ITEM_ID + 48] = { "shieldgold", "toggle" },
	[BASE_ITEM_ID + 50] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 51] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 52] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 53] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 54] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 55] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 56] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 57] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 58] = { "bottle", "consumable" },
	[BASE_ITEM_ID + 60] = { "daring5", "toggle" },

	-- Key Items
	[BASE_ITEM_ID + 89] = { "dragongem", "consumable" },
	[BASE_ITEM_ID + 90] = { "dragongem", "consumable" },
	[BASE_ITEM_ID + 91] = { "crown", "toggle" },
	[BASE_ITEM_ID + 92] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 93] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 94] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 95] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 96] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 97] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 98] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 99] = { "soulhelmet", "consumable" },
	[BASE_ITEM_ID + 100] = { "witchtalisman", "toggle" },
	[BASE_ITEM_ID + 101] = { "safekey", "toggle" },
	[BASE_ITEM_ID + 102] = { "shadowartefact", "toggle" },
	[BASE_ITEM_ID + 103] = { "shadowtalisman", "toggle" },
	[BASE_ITEM_ID + 104] = { "crucifix", "toggle" },
	[BASE_ITEM_ID + 105] = { "landlordsbust", "toggle" },
	[BASE_ITEM_ID + 106] = { "crucifixcast", "toggle" },
	[BASE_ITEM_ID + 107] = { "amber", "consumable" },
	[BASE_ITEM_ID + 108] = { "amber", "consumable" },
	[BASE_ITEM_ID + 109] = { "amber", "consumable" },
	[BASE_ITEM_ID + 110] = { "amber", "consumable" },
	[BASE_ITEM_ID + 111] = { "amber", "consumable" },
	[BASE_ITEM_ID + 112] = { "amber", "consumable" },
	[BASE_ITEM_ID + 113] = { "amber", "consumable" },
	[BASE_ITEM_ID + 114] = { "harvesterpart", "toggle" },
	[BASE_ITEM_ID + 115] = { "skullkey", "toggle" },
	[BASE_ITEM_ID + 116] = { "sheetmusic", "toggle" },

	-- Chaos Runes
	[BASE_ITEM_ID + 117] = { "chaosgrave", "toggle" },
	[BASE_ITEM_ID + 118] = { "chaoshill", "toggle" },
	[BASE_ITEM_ID + 119] = { "chaosscare", "toggle" },
	[BASE_ITEM_ID + 120] = { "chaoslake", "toggle" },
	[BASE_ITEM_ID + 121] = { "chaosgorge", "toggle" },
	[BASE_ITEM_ID + 122] = { "chaossleep", "toggle" },
	[BASE_ITEM_ID + 123] = { "chaospools", "toggle" },
	[BASE_ITEM_ID + 124] = { "chaosgrounds", "toggle" },
	[BASE_ITEM_ID + 125] = { "chaosruins", "toggle" },
	[BASE_ITEM_ID + 126] = { "chaosship", "toggle" },
	[BASE_ITEM_ID + 127] = { "chaosdevice", "toggle" },

	-- Earth Runes
	[BASE_ITEM_ID + 128] = { "earthgrave", "toggle" },
	[BASE_ITEM_ID + 129] = { "earthhill", "toggle" },
	[BASE_ITEM_ID + 130] = { "earthscare", "toggle" },
	[BASE_ITEM_ID + 131] = { "earthcrystal", "toggle" },
	[BASE_ITEM_ID + 132] = { "earthlake", "toggle" },
	[BASE_ITEM_ID + 133] = { "earthgorge", "toggle" },
	[BASE_ITEM_ID + 134] = { "earthsleep", "toggle" },
	[BASE_ITEM_ID + 135] = { "earthasylum", "toggle" },
	[BASE_ITEM_ID + 136] = { "earthenchant", "toggle" },
	[BASE_ITEM_ID + 137] = { "earthruins", "toggle" },
	[BASE_ITEM_ID + 138] = { "earthdevice", "toggle" },

	-- Moon Runes
	[BASE_ITEM_ID + 139] = { "moonhill", "toggle" },
	[BASE_ITEM_ID + 140] = { "moonscare", "toggle" },
	[BASE_ITEM_ID + 141] = { "moonsleep", "toggle" },
	[BASE_ITEM_ID + 142] = { "moongorge", "toggle" },
	[BASE_ITEM_ID + 143] = { "moonship", "toggle" },
	[BASE_ITEM_ID + 144] = { "moondevice", "toggle" },

	-- Star Runes
	[BASE_ITEM_ID + 145] = { "starreturn", "toggle" },
	[BASE_ITEM_ID + 146] = { "starcrypt", "toggle" },
	[BASE_ITEM_ID + 147] = { "starcrystal", "toggle" },
	[BASE_ITEM_ID + 148] = { "starlake", "toggle" },
	[BASE_ITEM_ID + 149] = { "starenchant", "toggle" },
	[BASE_ITEM_ID + 150] = { "stargorge", "toggle" },
	[BASE_ITEM_ID + 151] = { "stargallow", "toggle" },
	[BASE_ITEM_ID + 152] = { "starship", "toggle" },

	--Time Runes
	[BASE_ITEM_ID + 153] = { "timelake", "toggle" },
	[BASE_ITEM_ID + 154] = { "timegorge", "toggle" },
	[BASE_ITEM_ID + 155] = { "timedevice", "toggle" },

	--Traps
	[BASE_ITEM_ID + 156] = { "trap", "toggle" },
	[BASE_ITEM_ID + 157] = { "trap", "toggle" },
	[BASE_ITEM_ID + 158] = { "trap", "toggle" },
	[BASE_ITEM_ID + 159] = { "trap", "toggle" },

	-- Filler
	[BASE_ITEM_ID + 0] = { "filler", "toggle" },
	[BASE_ITEM_ID + 1] = { "filler", "toggle" },
	[BASE_ITEM_ID + 2] = { "filler", "toggle" },
	[BASE_ITEM_ID + 3] = { "filler", "toggle" },
	[BASE_ITEM_ID + 4] = { "filler", "toggle" },
	[BASE_ITEM_ID + 5] = { "filler", "toggle" },
	[BASE_ITEM_ID + 6] = { "filler", "toggle" },
	[BASE_ITEM_ID + 7] = { "filler", "toggle" },
	[BASE_ITEM_ID + 8] = { "filler", "toggle" },
	[BASE_ITEM_ID + 9] = { "filler", "toggle" },
	[BASE_ITEM_ID + 10] = { "filler", "toggle" },
	[BASE_ITEM_ID + 11] = { "filler", "toggle" },
	[BASE_ITEM_ID + 12] = { "filler", "toggle" },
	[BASE_ITEM_ID + 13] = { "filler", "toggle" },
	[BASE_ITEM_ID + 14] = { "filler", "toggle" },
	[BASE_ITEM_ID + 15] = { "filler", "toggle" },
	[BASE_ITEM_ID + 16] = { "filler", "toggle" },
	[BASE_ITEM_ID + 17] = { "filler", "toggle" },
	[BASE_ITEM_ID + 18] = { "filler", "toggle" },
	[BASE_ITEM_ID + 19] = { "filler", "toggle" },
	[BASE_ITEM_ID + 20] = { "filler", "toggle" },
	[BASE_ITEM_ID + 21] = { "filler", "toggle" },
	[BASE_ITEM_ID + 22] = { "filler", "toggle" },
	[BASE_ITEM_ID + 23] = { "filler", "toggle" },
	[BASE_ITEM_ID + 24] = { "filler", "toggle" },
	[BASE_ITEM_ID + 25] = { "filler", "toggle" },
	[BASE_ITEM_ID + 26] = { "filler", "toggle" },
	[BASE_ITEM_ID + 27] = { "filler", "toggle" },
	[BASE_ITEM_ID + 28] = { "small", "toggle" },
	[BASE_ITEM_ID + 29] = { "medium", "toggle" },
	[BASE_ITEM_ID + 30] = { "large", "toggle" }


}


Medi_II_Items = {
	[9901000] = { "filler", "toggle" },
	[9901001] = { "filler", "toggle" },
	[9901002] = { "filler", "toggle" },
	[9901003] = { "small", "toggle" },
	[9901004] = { "medium", "toggle" },
	[9901005] = { "large", "toggle" },
	[9901006] = { "filler", "toggle" },
	[9901007] = { "filler", "toggle" },
	[9901008] = { "filler", "toggle" },
	[9901009] = { "filler", "toggle" },
	[9901010] = { "filler", "toggle" },
	[9901011] = { "filler", "toggle" },
	[9901012] = { "filler", "toggle" },
	[9901013] = { "filler", "toggle" },
	[9901014] = { "filler", "toggle" },
	[9901015] = { "filler", "toggle" },
	[9901016] = { "filler", "toggle" },
	[9901017] = { "filler", "toggle" },
	[9901018] = { "filler", "toggle" },
	[9901019] = { "filler", "toggle" },
	[9901020] = { "filler", "toggle" },
	[9901021] = { "filler", "toggle" },
	[9901022] = { "filler", "toggle" },
	[9901023] = { "filler", "toggle" },
	[9901024] = { "filler", "toggle" },
	[9901025] = { "filler", "toggle" },
	[9901026] = { "filler", "toggle" },
	[9901027] = { "filler", "toggle" },
	[9901028] = { "filler", "toggle" },
	[9901029] = { "filler", "toggle" },
	[9901030] = { "filler", "toggle" },
	[9901031] = { "filler", "toggle" },
	[9901032] = { "Small Sword", "toggle" },
	[9901033] = { "Broad Sword", "toggle" },
	[9901034] = { "Magic Sword", "toggle" },
	[9901035] = { "Cane", "toggle" },
	[9901036] = { "Hammer", "toggle" },
	[9901037] = { "Axe", "toggle" },
	[9901038] = { "Pistol", "toggle" },
	[9901039] = { "Crossbow", "toggle" },
	[9901040] = { "Flaming", "toggle" },
	[9901041] = { "Gatling", "toggle" },
	[9901042] = { "Good Lightning", "toggle" },
	[9901043] = { "Lightning", "toggle" },
	[9901044] = { "Blunderbuss", "toggle" },
	[9901045] = { "Bombs", "toggle" },
	[9901046] = { "Chicken Drumsticks", "toggle" },
	[9901047] = { "Copper Shield", "toggle" },
	[9901048] = { "Silver Shield", "toggle" },
	[9901049] = { "Gold Shield", "toggle" },
	[9901050] = { "life_bottles", "consumable" },
	[9901051] = { "Armour", "toggle" },
	[9901052] = { "Hand", "toggle" },
	[9901053] = { "Poster", "toggle" },
	--[9901052] = { "Left Leg", "toggle" },
	--[9901053] = { "Right Leg", "toggle" },
	--[9901054] = { "Left Arm", "toggle" },
	--[9901055] = { "Right Arm", "toggle" },
	--[9901056] = { "Bum", "toggle" },
	--[9901057] = { "Torso", "toggle" },
	[9901058] = { "Bellows", "toggle" },
	[9901059] = { "Lost Soul", "consumable" },
	[9901060] = { "Golden Cog", "consumable" },
	[9901061] = { "Spell Page", "toggle" },
	[9901062] = { "Griffin Shield", "toggle" },
	[9901063] = { "Unicorn Shield", "toggle" },
	[9901064] = { "Beard", "toggle" },
	[9901065] = { "librarykey", "toggle" },
	[9901066] = { "card", "toggle" },
	[9901067] = { "elephantkey1", "toggle" },
	[9901068] = { "elephantkey2", "toggle" },
	[9901069] = { "TMContact", "toggle" },
	[9901070] = { "TMEarth", "toggle" },
	[9901071] = { "TMSpace", "toggle" },
	[9901072] = { "kingkey", "toggle" },
	[9901073] = { "Staff", "toggle" },
	[9901074] = { "Scroll", "toggle" },
	[9901075] = { "Tablet", "toggle" },
	[9901076] = { "Pocket Watch", "toggle" },
	[9901077] = { "townhousekey", "toggle" },
	[9901078] = { "Time Stone", "toggle" },
	[9901079] = { "Antidote", "toggle" },
	[9901080] = { "Pond Room Valve", "toggle" },
	[9901081] = { "Hothouse Valve", "toggle" },
	[9901082] = { "Water Tank Valve", "toggle" },
	[9901083] = { "cannonball", "toggle" },
	[9901084] = { "frontdoorkey", "toggle" },
	[9901085] = { "shedkey", "toggle" },
	[9901086] = { "depotkey", "toggle" },
	[9901087] = { "museumkey", "toggle" },
	[9901088] = { "dinokey", "toggle" },
	[9901089] = { "Torch", "toggle" },
	[9901090] = { "Trap", "toggle" },
	[9901091] = { "Trap", "toggle" },
	[9901092] = { "Trap", "toggle" },
	[9901093] = { "Trap", "toggle" }
}
